
var answers = {
        "Listening-Part1-Question1":"Jack was once a student in Winnipeg.",
        "Listening-Part1-Question2":"I'm fixing the car now.",
        "Listening-Part1-Question3":"Sam won't be home for a while.",
        "Listening-Part1-Question4":"Phil missed the end of the movie.",
        "Listening-Part1-Question5":"Wendy was promoted.",
        "Listening-Part1-Question6":"You decide when to pay.",
        "Listening-Part1-Question7":"I need to postpone my trip.",
        "Listening-Part1-Question8":"Lately, Jacob works very little.", 
        "Listening-Part2-Question1":"You should probably get a taxi from here.",
        "Listening-Part2-Question2":"It was pretty dull if you ask me.", 
        "Listening-Part2-Question3":"Quite a bit since it's high season.",
        "Listening-Part2-Question4":"I'm looking for the manager.", 
        "Listening-Part2-Question5":"She was out of town.", 
        "Listening-Part2-Question6":"I think your old one will do just fine.",
        "Listening-Part2-Question7":"It's about halfway done.",
        "Listening-Part2-Question8":"There are many positions advertised.", 
        "Listening-Part3-Question1":"He missed an interview opportunity.", 
        "Listening-Part3-Question2":"She had a family emergency.", 
        "Listening-Part3-Question3":"She only meets journalists face to face.",
        "Listening-Part3-Question4":"Try to interview the artist while she's in New York.",
        "Listening-Part3-Question5":"Fill in for her for five days.",
        "Listening-Part4-Question1":"Slugs have attacked part of her vegetable garden.",
        "Listening-Part4-Question2":"There has been an excessive amount of rain.",
        "Listening-Part4-Question3":"They make the environment unpleasant for slugs.",
        "Listening-Part4-Question4":"The pests cannot cross over the coils.", 
        "Listening-Part4-Question5":"The woman can use 1 cent coins.",
        "Listening-Part4-Question6":"To purchase an item that is currently out of stock.",
        "Listening-Part5-Question1":"it jumped onto him.",
        "Listening-Part5-Question2":"was part of a research project.",
        "Listening-Part5-Question3":"is studying animal language.",
        "Listening-Part5-Question4":"stayed at Henry Lang's house for a couple of days.",
        "Listening-Part5-Question5":"now teaches the parrot opera singing.",
        "Listening-Part6-Question1":"has received a lot of opposition.",
        "Listening-Part6-Question2":"lead to the growth of toxic organisms in the sea.",
        "Listening-Part6-Question3":"competition between farmed and native species.",
        "Listening-Part6-Question4":"positively impacts bird and dolphin populations.", 
        "Listening-Part6-Question5":"contain organisms that can be harmful for humans.",
        "Listening-Part6-Question6":"marketing maneuvers to dissuade consumption of farmed fish."
}		

